const mongoose = require('mongoose');

const SkillGapSchema = new mongoose.Schema({
  userId: { type: String, required: true },
  targetRole: { type: String, required: true },
  resumeFileName: { type: String, default: 'resume.pdf' },
  readinessScore: { type: Number, default: 0 },
  skillMatchPercentage: { type: Number, default: 0 },
  skillsYouHave: [{ type: String }],
  skillsToImprove: [{
    skill: String,
    status: { type: String, default: 'Missing' },
    importance: { type: String, enum: ['High', 'Medium', 'Low'], default: 'High' },
    reason: String,
    action: String
  }],
  scoreBreakdown: {
    coreTechnical: { type: Number, default: 0 },
    supportingSkills: { type: Number, default: 0 },
    experienceAlignment: { type: Number, default: 0 },
    educationAlignment: { type: Number, default: 0 },
    resumeEvidenceQuality: { type: Number, default: 0 }
  },
  skillsBreakdown: [{
    skill: String,
    level: Number,
    status: { type: String, enum: ['Present', 'Partial', 'Missing'], default: 'Present' },
    evidence: String
  }],
  requiredSkills: [{ type: String }],
  existingSkills: [{ type: String }],
  missingSkills: [{ type: String }],
  prioritySkills: [{
    skill: String,
    reason: String,
    suggestedAction: String
  }],
  note: { 
    type: String, 
    default: 'Skill gaps are generated by comparing your uploaded resume with the requirements for your selected target role. Review the results and update your profile if any skill is missing from your resume.' 
  },
  analyzedAt: { type: Date, default: Date.now }
}, { timestamps: true });

module.exports = mongoose.model('SkillGap', SkillGapSchema);
